[project]
docs_dir = "pages/"
site_dir = "build/"

site_name = "LazyGate"
site_url = "https://lazygate.kasefuchs.net"

repo_url = "https://github.com/kasefuchs/lazygate"
repo_name = "kasefuchs/lazygate"
edit_uri = "edit/main/docs/pages"

nav = [
  { "Home" = "index.md" },
  { "Installation" = [
    { "Docker" = "install/docker.md" },
    { "Plugin" = "install/plugin.md" }
  ] }
]

[project.theme]
language = "en"
features = [
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "navigation.footer",
  "navigation.instant",
  "navigation.instant.progress",
  "navigation.tabs",
  "navigation.top",
  "search.highlight"
]

[project.theme.icon]
logo = "lucide/bed"
repo = "lucide/github"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "indigo"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "orange"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
